### ISSUE TITLE
Possibly Sandbox Extension Environment

### ISSUE THREAD

**Issue by MPierre9** [marcobeltempo/chaddon#49]
As discussed in meeting on March 7th 2018. We might need to sandbox our application to get googles approval

**Comment by marcobeltempo** [comment]
Resources from the meeting:

Bugs
----------------------------------
Getting approved for Chrome store
- implementing a sandboxed enviroment
- reach out to Google help
- re-read requirements

Links
[browser-extensions-and-csp-headers](https://transitory.technology/browser-extensions-and-csp-headers/)
[injecting-iframe-into-page-with-restrictive-content-security-policy](https://stackoverflow.com/questions/24641592/injecting-iframe-into-page-with-restrictive-content-security-policy)

ex. (https://github.com/onmyway133/github-chat)

**Comment by MPierre9** [comment]
Closing for now
