### ISSUE TITLE
Guest users are placed into a general chat. Should be added to tab URL channel

### ISSUE THREAD

**Issue by marcobeltempo** [marcobeltempo/chaddon#58]
Right now guest users are placed into a global socket channel. We need to pass a `payload.domain` similar to how we pass it to a Google user.
[/browser_extension/src/bg/authentication.j](https://github.com/marcobeltempo/chaddon/blob/dev/browser_extension/src/bg/authentication.js#L57-L62)

**Comment by GeoffMcCollam** [comment]
Guests are put in URL channel in the version in my repo.
